# Deploys a new Namespace for the MinIO Pod
apiVersion: v1
kind: Namespace
metadata:
  name: minio
  labels:
    name: minio
---
apiVersion: v1
kind: Secret
metadata:
  name: minio
  namespace: minio
type: Opaque
data:
  # 9b744078-f094-40d7-a1da-3b7dfd7cf50b
  accesskey: OWI3NDQwNzgtZjA5NC00MGQ3LWExZGEtM2I3ZGZkN2NmNTBi
  # 184a7319-797d-473a-aa8c-94f2017e87a2
  secretkey: MTg0YTczMTktNzk3ZC00NzNhLWFhOGMtOTRmMjAxN2U4N2Ey
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minio
  namespace: minio
spec:
  selector:
    matchLabels:
      app: minio
  serviceName: minio
  replicas: 1
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
      - name: minio
        image: quay.io/minio/minio:latest
        command:
        - /bin/bash
        - -c
        args:
        - minio server /data --console-address :9001
        ports:
        - containerPort: 9000
          name: service
        - containerPort: 9001
          name: console
        env:
          - name: MINIO_ROOT_USER
            valueFrom:
              secretKeyRef:
                name: minio
                key: accesskey
          - name: MINIO_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: minio
                key: secretkey
        volumeMounts:
        - name: localvolume
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: localvolume
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: minio
spec:
  selector:
    app: minio
  ports:
  - name: service
    port: 9000
    targetPort: service
    protocol: TCP
  - name: console
    port: 9001
    targetPort: console
    protocol: TCP
